services:
  - type: web
    name: sports-vision-trainer-backend
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: BASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: SMTP_SENDER_EMAIL
        sync: false
      - key: SMTP_SENDER_PASSWORD
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
